/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminEventsRouteImport } from './routes/_authenticated/_admin/admin.events'
import { Route as AuthenticatedAdminAdminSalesRouteImport } from './routes/_authenticated/_admin/admin.sales'
import { Route as AuthenticatedAdminAdminTicketsRouteImport } from './routes/_authenticated/_admin/admin.tickets'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/_authenticated/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/_authenticated/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/_authenticated/_admin/admin/',
    path: '/admin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminEventsRoute =
  AuthenticatedAdminAdminEventsRouteImport.update({
    id: '/_authenticated/_admin/admin/events',
    path: '/admin/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminSalesRoute =
  AuthenticatedAdminAdminSalesRouteImport.update({
    id: '/_authenticated/_admin/admin/sales',
    path: '/admin/sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminTicketsRoute =
  AuthenticatedAdminAdminTicketsRouteImport.update({
    id: '/_authenticated/_admin/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/_authenticated/_admin/admin/users',
    path: '/admin/users',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events': typeof AuthenticatedAdminAdminEventsRoute
  '/admin/sales': typeof AuthenticatedAdminAdminSalesRoute
  '/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/admin/events': typeof AuthenticatedAdminAdminEventsRoute
  '/admin/sales': typeof AuthenticatedAdminAdminSalesRoute
  '/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/_admin/admin/events': typeof AuthenticatedAdminAdminEventsRoute
  '/_authenticated/_admin/admin/sales': typeof AuthenticatedAdminAdminSalesRoute
  '/_authenticated/_admin/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/purchases'
    | '/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/admin/events'
    | '/admin/sales'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/purchases'
    | '/tickets'
    | '/events/$eventId'
    | '/events'
    | '/admin/events'
    | '/admin/sales'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/_authenticated/purchases'
    | '/_authenticated/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/_authenticated/_admin/admin/events'
    | '/_authenticated/_admin/admin/sales'
    | '/_authenticated/_admin/admin/tickets'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AuthenticatedAdminAdminEventsRoute: typeof AuthenticatedAdminAdminEventsRoute
  AuthenticatedAdminAdminSalesRoute: typeof AuthenticatedAdminAdminSalesRoute
  AuthenticatedAdminAdminTicketsRoute: typeof AuthenticatedAdminAdminTicketsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/events': {
      id: '/_authenticated/_admin/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminAdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/sales': {
      id: '/_authenticated/_admin/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminAdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/tickets': {
      id: '/_authenticated/_admin/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminAdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  AuthenticatedAdminAdminEventsRoute: AuthenticatedAdminAdminEventsRoute,
  AuthenticatedAdminAdminSalesRoute: AuthenticatedAdminAdminSalesRoute,
  AuthenticatedAdminAdminTicketsRoute: AuthenticatedAdminAdminTicketsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
